version: '3.2'

services:

  dd_flow_api_app:
    tty: true
    build:
      context: .
      args:
        requirements: requirements/production.txt
    container_name: dd-flow
    environment:
      - SETTINGS_FILE=api.prod.yml
      - PYTHONPATH=/app
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error}]
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis
      - rabbitmq
    entrypoint: "python3 api/data_delivery_flow_api/main.py"
    ports:
      - 8080:8080
    expose:
      - "8080"

  redis:
    image: redis:4
    ports:
        - 6379

  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    expose:
      - "5672"
      - "15672"
    ports:
      - 5672
      - 15672