version: '3.2'

services:

  dd_flow_api_app: &app
    tty: true
    build:
      context: .
      args:
        requirements: requirements/development.txt
    container_name: api
    environment:
      # use in code
      - DEBUG=True
      - SETTINGS_FILE=api.dev.yml
      - PYTHONUNBUFFERED=1
    restart: always
    volumes:
      - .:/app:delegated
    depends_on:
      - redis
    ports:
      - 8080:8080
      - 8081:8081
    command: make adev

  redis:
    image: redis:4
    ports:
        - 6379

  test:
    <<: *app
    container_name: dd_flow_api_test
    ports:
      - 8082:8082
    command: make _test
