app:
  host: localhost
  port: 8000

redis:
  host: localhost
  port: 6379
  db: 0

rabbitmq:
  host: rabbitmq
  port: 5672
  queue: dd-items
  exchange_name: dd-exchange
  exchange_type: direct
  routing_key: dd-items
